"""
bridge.py — orchestrates the full SPHINCS+ ZK proof pipeline:

  1. Generate SPHINCS+ keypair
  2. Build + sign a Stellar XDR transaction
  3. Export proof_inputs.json
  4. Run the RISC Zero host prover (cargo run)
  5. Read proof.json
  6. Print the stellar CLI command to verify on-chain via Soroban

Usage:
    uv run --python .venv/bin/python bridge.py

Proving modes (checked in order):
  Boundless network (Groth16, no local GPU needed):
    BOUNDLESS_RPC_URL        — Base Sepolia RPC, e.g. https://sepolia.base.org
    BOUNDLESS_PRIVATE_KEY    — hex private key of your Base Sepolia wallet (needs testnet ETH)
    BOUNDLESS_ORDER_STREAM_URL — defaults to https://base-sepolia.boundless.network
    PINATA_JWT               — Pinata API JWT for storing guest ELF (free tier ok)
                               OR set S3_BUCKET + AWS_* for S3 storage

  Local dev mode (STARK only, no Groth16, no on-chain verify):
    omit BOUNDLESS_RPC_URL   — falls back to local CPU proving (slow)

Soroban:
    VERIFIER_CONTRACT_ID — Nethermind Groth16 verifier contract on Stellar testnet
    SPHINCS_CONTRACT_ID  — your deployed Soroban wrapper contract

Get free Base Sepolia ETH: https://www.coinbase.com/en-gb/faucets/base-ethereum-goerli-faucet
Get free Pinata account:   https://app.pinata.cloud
"""

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path

# Auto-load .env if present
_env_file = Path(__file__).parent / ".env"
if _env_file.exists():
    for line in _env_file.read_text().splitlines():
        line = line.strip()
        if line and not line.startswith("#") and "=" in line:
            k, _, v = line.partition("=")
            os.environ.setdefault(k.strip(), v.strip())

# Project root
ROOT = Path(__file__).parent
PROVER_DIR = ROOT / "prover"
PROOF_INPUTS = ROOT / "proof_inputs.json"
PROOF_OUTPUT = ROOT / "proof.json"


def run_step(label: str, fn):
    print(f"\n{'='*60}")
    print(f"  {label}")
    print(f"{'='*60}")
    return fn()


def step_keygen_and_sign():
    # Import from sphincs.py
    sys.path.insert(0, str(ROOT))
    from sphincs import generate_keypair, build_stellar_tx_bytes, sign_tx_bytes, export_proof_inputs

    pub, priv = generate_keypair()
    print(f"Public key  ({len(pub)} bytes): {pub.hex()[:48]}...")

    tx_bytes = build_stellar_tx_bytes()
    print(f"Stellar XDR ({len(tx_bytes)} bytes): {tx_bytes[:32]}...")

    sig = sign_tx_bytes(tx_bytes, priv)
    print(f"Signature   ({len(sig)} bytes): {sig.hex()[:48]}...")

    export_proof_inputs(pub, tx_bytes, sig, path=str(PROOF_INPUTS))
    return pub, tx_bytes, sig


def step_prove():
    env = os.environ.copy()
    use_boundless = bool(os.environ.get("BOUNDLESS_RPC_URL"))

    cmd = [
        "cargo", "+risc0", "run",
        "--release",
        "--manifest-path", str(PROVER_DIR / "Cargo.toml"),
        "-p", "sphincs-host",
    ]
    if use_boundless:
        cmd += ["--features", "boundless"]
        print("Boundless mode: proof will be generated by the network (Groth16)")
    else:
        print("Local mode: proof will be generated on this machine (STARK, slow)")

    cmd += ["--", str(PROOF_INPUTS), str(PROOF_OUTPUT)]
    print(f"Running: {' '.join(cmd)}")
    result = subprocess.run(cmd, env=env)
    if result.returncode != 0:
        print("\nProver failed. Check Cargo output above.")
        sys.exit(1)


def step_print_soroban_cmd():
    proof = json.loads(PROOF_OUTPUT.read_text())

    verifier_id = os.environ.get("VERIFIER_CONTRACT_ID", "<NETHERMIND_VERIFIER_CONTRACT_ID>")
    sphincs_id  = os.environ.get("SPHINCS_CONTRACT_ID", "<YOUR_SPHINCS_CONTRACT_ID>")

    print(f"\nProof ready:")
    print(f"  image_id:    {proof['image_id'][:32]}...")
    print(f"  journal:     {proof['journal'][:32]}...")
    print(f"  pubkey_hash: {proof['pubkey_hash']}")
    print(f"  tx_hash:     {proof['tx_hash']}")

    print(f"\nTo verify on Stellar testnet:")
    print(f"""
stellar contract invoke \\
  --id {sphincs_id} \\
  --source-account YOUR_SECRET_KEY \\
  --network testnet \\
  -- verify_sphincs_tx \\
  --seal {proof['seal'][:32]}... \\
  --image_id {proof['image_id']} \\
  --journal {proof['journal']} \\
  --pubkey_hash {proof['pubkey_hash']} \\
  --tx_hash {proof['tx_hash']}
""")
    print(f"Nethermind verifier contract: {verifier_id}")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--skip-sign", action="store_true",
                        help="Skip key gen/signing, reuse existing proof_inputs.json")
    args = parser.parse_args()

    if not args.skip_sign:
        run_step("Step 1: SPHINCS+ keygen + Stellar XDR sign", step_keygen_and_sign)
    else:
        print("Skipping sign step, using existing proof_inputs.json")

    run_step("Step 2: RISC Zero proving", step_prove)
    run_step("Step 3: Soroban invocation", step_print_soroban_cmd)

    print("\nDone.")


if __name__ == "__main__":
    main()
